# Generated by Django 4.0.3 on 2022-04-09 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='swimspot',
            name='is_approved',
        ),
    ]
