# Generated by Django 4.0.3 on 2022-05-02 18:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 2, 18, 34, 35, 302711, tzinfo=utc), max_length=64),
        ),
    ]
