# Generated by Django 4.0.3 on 2022-04-09 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_swimspot_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='swimspot',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
