# Generated by Django 4.0.3 on 2022-04-11 19:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_swimspot_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 11, 19, 2, 57, 922514, tzinfo=utc), max_length=64),
        ),
    ]
