# Generated by Django 4.0.3 on 2022-04-15 19:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_comment_date_added_alter_comment_swim_id_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 15, 19, 35, 34, 492831, tzinfo=utc), max_length=64),
        ),
    ]
