# Generated by Django 4.0.3 on 2022-04-15 20:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_photo_swim_id_alter_comment_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 15, 20, 19, 20, 962384, tzinfo=utc), max_length=64),
        ),
    ]
