# Generated by Django 4.0.3 on 2022-04-16 15:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_comment_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 16, 15, 32, 15, 995294, tzinfo=utc), max_length=64),
        ),
    ]
