# Generated by Django 4.0.3 on 2022-04-20 13:50

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_alter_comment_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='swimspot',
            name='location',
        ),
        migrations.AddField(
            model_name='location',
            name='swimspot',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalog.swimspot'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 20, 13, 49, 53, 364130, tzinfo=utc), max_length=64),
        ),
    ]
