# Generated by Django 4.0.3 on 2022-04-20 13:51

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_remove_swimspot_location_location_swimspot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 20, 13, 51, 18, 741982, tzinfo=utc), max_length=64),
        ),
        migrations.AlterField(
            model_name='location',
            name='swimspot',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalog.swimspot'),
        ),
    ]
