# Generated by Django 4.0.3 on 2022-04-20 14:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_alter_comment_date_added_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 20, 14, 8, 33, 752707, tzinfo=utc), max_length=64),
        ),
    ]
