# Generated by Django 4.0.3 on 2022-04-29 19:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_alter_comment_date_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('events_completed', models.CharField(max_length=500)),
                ('training_for', models.CharField(max_length=500)),
                ('blurb', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='photos/')),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 29, 19, 56, 17, 189474, tzinfo=utc), max_length=64),
        ),
    ]
