# Generated by Django 4.0.3 on 2022-05-01 20:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0028_remove_comment_id_alter_comment_date_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 1, 20, 49, 17, 370404, tzinfo=utc), max_length=64),
        ),
    ]
