# Generated by Django 4.0.3 on 2022-05-15 16:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_comment_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 15, 16, 4, 58, 181733, tzinfo=utc), max_length=64),
        ),
    ]
