# Generated by Django 4.0.3 on 2022-06-21 17:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_alter_comment_date_added_alter_savedswims_swim_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 21, 17, 55, 57, 340051, tzinfo=utc), max_length=64),
        ),
    ]
