# Generated by Django 4.0.6 on 2022-08-09 19:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_alter_comment_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 9, 19, 37, 11, 227235, tzinfo=utc), max_length=64),
        ),
    ]
