# Generated by Django 4.0.6 on 2022-08-10 17:12

import cloudinary.models
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_alter_comment_date_added_alter_photo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 10, 17, 12, 23, 958836, tzinfo=utc), max_length=64),
        ),
        migrations.AlterField(
            model_name='profilepic',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
