# Generated by Django 4.0.6 on 2022-08-11 16:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_alter_comment_date_added_alter_profilepic_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='title',
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 11, 16, 45, 41, 451329, tzinfo=utc), max_length=64),
        ),
    ]
